import discord
import logging
from typing import Dict
from redbot.core import commands, Config
from redbot.core.bot import Red
from datetime import datetime, timezone

log = logging.getLogger("red.invitetracking")


class InviteView(discord.ui.View):
    """Persistent button view for generating invite links."""

    def __init__(self, cog: "InviteTracking"):
        super().__init__(timeout=None)
        self.cog = cog

    @discord.ui.button(
        label="Generate Invite",
        style=discord.ButtonStyle.primary,
        custom_id="invitetracking_generate"
    )
    async def generate_invite(
        self, interaction: discord.Interaction, button: discord.ui.Button
    ):
        guild = interaction.guild
        channel = interaction.channel

        if not channel.permissions_for(guild.me).create_instant_invite:
            await interaction.response.send_message(
                "I don't have permission to create invites in this channel.",
                ephemeral=True
            )
            return

        await interaction.response.defer(ephemeral=True)

        try:
            invite = await channel.create_invite(
                max_uses=1,
                max_age=86400,
                reason=f"Generated by {interaction.user} via InviteTracking"
            )
        except discord.HTTPException as e:
            await interaction.followup.send(
                f"Failed to create invite: {e}", ephemeral=True
            )
            return

        stored = await self.cog.config.guild(guild).invites()
        stored[invite.code] = {
            "creator_id": interaction.user.id,
            "creator_name": str(interaction.user),
            "channel_id": channel.id,
            "uses": 0,
            "used_by": [],
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        await self.cog.config.guild(guild).invites.set(stored)

        cache = await self.cog._get_invite_cache(guild)
        cache[invite.code] = 0
        await self.cog.config.guild(guild).invite_cache.set(cache)

        await interaction.followup.send(
            f"One-time invite created: {invite.url}\nExpires in 24 hours.",
            ephemeral=True
        )


class InviteTracking(commands.Cog):
    """Track who uses invite links generated via the invite button."""

    def __init__(self, bot: Red):
        self.bot = bot
        self.config = Config.get_conf(self, identifier=739182465, force_registration=True)

        default_guild = {
            "setup_channel": None,
            "setup_message": None,
            "invites": {},
            "invite_cache": {},
        }
        self.config.register_guild(**default_guild)

        bot.loop.create_task(self._initialize())

    async def _initialize(self):
        await self.bot.wait_until_ready()

        all_data = await self.config.all_guilds()
        for guild_id, data in all_data.items():
            msg_id = data.get("setup_message")
            if msg_id:
                self.bot.add_view(InviteView(self), message_id=msg_id)

        for guild in self.bot.guilds:
            await self._refresh_invite_cache(guild)

        log.info("InviteTracking cog initialized")

    async def _refresh_invite_cache(self, guild: discord.Guild):
        try:
            invites = await guild.invites()
        except (discord.Forbidden, discord.HTTPException):
            return

        cache = {}
        for inv in invites:
            cache[inv.code] = inv.uses
        await self.config.guild(guild).invite_cache.set(cache)

    async def _get_invite_cache(self, guild: discord.Guild) -> Dict[str, int]:
        return await self.config.guild(guild).invite_cache() or {}

    @commands.Cog.listener()
    async def on_member_join(self, member: discord.Member):
        if member.bot:
            return

        guild = member.guild

        try:
            current_invites = await guild.invites()
        except (discord.Forbidden, discord.HTTPException):
            return

        old_cache = await self._get_invite_cache(guild)
        new_cache = {}
        used_code = None

        for inv in current_invites:
            new_cache[inv.code] = inv.uses
            old_uses = old_cache.get(inv.code, 0)
            if inv.uses > old_uses:
                used_code = inv.code

        await self.config.guild(guild).invite_cache.set(new_cache)

        if not used_code:
            return

        stored = await self.config.guild(guild).invites()
        if used_code not in stored:
            return

        stored[used_code]["uses"] = new_cache[used_code]
        if member.id not in stored[used_code]["used_by"]:
            stored[used_code]["used_by"].append(member.id)
        await self.config.guild(guild).invites.set(stored)

        log.info(
            "%s joined %s using invite %s (created by %s)",
            member, guild.name, used_code,
            stored[used_code].get("creator_name", "unknown")
        )

    @commands.Cog.listener()
    async def on_invite_delete(self, invite: discord.Invite):
        guild = invite.guild
        if guild is None:
            return

        stored = await self.config.guild(guild).invites()
        stored.pop(invite.code, None)
        await self.config.guild(guild).invites.set(stored)

        cache = await self._get_invite_cache(guild)
        cache.pop(invite.code, None)
        await self.config.guild(guild).invite_cache.set(cache)

    @commands.group(name="invites", aliases=["invitetracking"])
    @commands.guild_only()
    async def invites(self, ctx: commands.Context):
        """Manage invite tracking."""
        if ctx.invoked_subcommand is None:
            await ctx.send_help()

    @invites.command(name="setup")
    @commands.admin_or_permissions(manage_guild=True)
    async def invites_setup(self, ctx: commands.Context, channel: discord.TextChannel = None):
        """Place the invite generation button in a channel."""
        channel = channel or ctx.channel

        if not channel.permissions_for(ctx.guild.me).create_instant_invite:
            await ctx.send("I need the **Create Invite** permission in that channel.")
            return

        view = InviteView(self)
        embed = discord.Embed(
            title="Generate an Invite Link",
            description=(
                "Click the button below to create a one-time invite link.\n"
                "Each invite expires after 24 hours."
            ),
            color=discord.Color.blue()
        )
        msg = await channel.send(embed=embed, view=view)

        await self.config.guild(ctx.guild).setup_channel.set(channel.id)
        await self.config.guild(ctx.guild).setup_message.set(msg.id)

        await ctx.send(f"Invite tracking set up in {channel.mention}.")

    @invites.command(name="channel")
    async def invites_channel(self, ctx: commands.Context):
        """Show the configured invite channel."""
        channel_id = await self.config.guild(ctx.guild).setup_channel()
        if channel_id:
            channel = ctx.guild.get_channel(channel_id)
            if channel:
                await ctx.send(f"Invite button is in {channel.mention}.")
                return
        await ctx.send("No invite channel has been configured.")

    @invites.command(name="list")
    async def invites_list(self, ctx: commands.Context):
        """List all tracked invites and their usage."""
        stored = await self.config.guild(ctx.guild).invites()
        if not stored:
            await ctx.send("No invites have been created yet.")
            return

        embed = discord.Embed(
            title="Invite Tracking",
            color=discord.Color.blue()
        )

        for code, data in list(stored.items())[:10]:
            creator = ctx.guild.get_member(data["creator_id"])
            creator_name = creator.mention if creator else data.get("creator_name", "Unknown")
            used_by = data.get("used_by", [])
            members = []
            for uid in used_by[:5]:
                m = ctx.guild.get_member(uid)
                members.append(m.mention if m else f"<@{uid}>")
            member_str = ", ".join(members) if members else "None yet"
            if len(used_by) > 5:
                member_str += f" (+{len(used_by) - 5} more)"

            embed.add_field(
                name=f"`{code}` — {len(used_by)} use(s)",
                value=f"Creator: {creator_name}\nUsers: {member_str}",
                inline=False
            )

        total = sum(len(d.get("used_by", [])) for d in stored.values())
        embed.set_footer(text=f"{len(stored)} invite(s) · {total} total join(s)")
        await ctx.send(embed=embed)

    @invites.command(name="user", aliases=["member"])
    async def invites_user(self, ctx: commands.Context, member: discord.Member = None):
        """Show invites created by or used by a member."""
        member = member or ctx.author
        stored = await self.config.guild(ctx.guild).invites()

        created = []
        used = []
        for code, data in stored.items():
            if data["creator_id"] == member.id:
                created.append(code)
            if member.id in data.get("used_by", []):
                used.append(code)

        embed = discord.Embed(
            title=f"Invite Stats — {member.display_name}",
            color=discord.Color.blue()
        )
        embed.add_field(name="Invites Created", value=str(len(created)), inline=True)
        embed.add_field(name="Invites Used", value=str(len(used)), inline=True)

        if created:
            lines = []
            for code in created[:5]:
                u = len(stored[code].get("used_by", []))
                lines.append(f"`{code}` — {u} join(s)")
            embed.add_field(
                name="Recent Created",
                value="\n".join(lines) or "None",
                inline=False
            )

        if used:
            lines = []
            for code in used[:5]:
                u = len(stored[code].get("used_by", []))
                lines.append(f"`{code}` — {u} join(s)")
            embed.add_field(
                name="Recent Used",
                value="\n".join(lines) or "None",
                inline=False
            )

        await ctx.send(embed=embed)

    @invites.command(name="clear")
    @commands.admin_or_permissions(manage_guild=True)
    async def invites_clear(self, ctx: commands.Context):
        """Clear all stored invite data for this server."""
        await self.config.guild(ctx.guild).invites.set({})
        await self.config.guild(ctx.guild).invite_cache.set({})
        await ctx.send("All invite data cleared.")

    @invites.command(name="remove")
    @commands.admin_or_permissions(manage_guild=True)
    async def invites_remove(self, ctx: commands.Context):
        """Remove the invite button message and clean up."""
        channel_id = await self.config.guild(ctx.guild).setup_channel()
        msg_id = await self.config.guild(ctx.guild).setup_message()

        if msg_id and channel_id:
            channel = ctx.guild.get_channel(channel_id)
            if channel:
                try:
                    msg = await channel.fetch_message(msg_id)
                    await msg.delete()
                except (discord.NotFound, discord.HTTPException):
                    pass

        await self.config.guild(ctx.guild).setup_channel.set(None)
        await self.config.guild(ctx.guild).setup_message.set(None)
        await ctx.send("Invite button removed.")
